language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed markus2101/udagram-api-feed:v1
  - docker tag udagram-api-user markus2101/udagram-api-user:v1
  - docker tag udagram-api-frontend markus2101/udagram-api-frontend:v1
  - docker tag reverseproxy markus2101/reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push markus2101/udagram-api-feed:v1
  - docker push markus2101/udagram-api-user:v1
  - docker push markus2101/udagram-api-frontend:v1
  - docker push markus2101/reverseproxy:v1
