name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image 'udagram-api-feed'
      run: docker build -t udagram-api-feed ./udagram-api-feed
    - name: Build the Docker image 'udagram-api-user'
      run: docker build -t udagram-api-user ./udagram-api-user
    - name: Build the Docker image 'udagram-frontend'
      run: docker build -t udagram-frontend ./udagram-frontend
    - name: Build the Docker image 'reverseproxy'
      run: docker build -t reverseproxy ./udagram-reverseproxy

    - name: Tag the Docker image 'udagram-api-feed'
      run: docker tag udagram-api-feed markus2101/udagram-api-feed:v1
    - name: Tag the Docker image 'udagram-api-user'
      run: docker tag udagram-api-user markus2101/udagram-api-user:v1
    - name: Tag the Docker image 'udagram-frontend'
      run: docker tag udagram-frontend markus2101/udagram-frontend:v1
    - name: Tag the Docker image 'reverseproxy'
      run: docker tag reverseproxy markus2101/reverseproxy:v1

    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Push Docker image 'udagram-api-feed' to Docker Hub
      run: docker push markus2101/udagram-api-feed:v1
    - name: Push Docker image 'udagram-api-user' to Docker Hub
      run: docker push markus2101/udagram-api-user:v1
    - name: Push Docker image 'udagram-frontend' to Docker Hub
      run: docker push markus2101/udagram-frontend:v1
    - name: Push Docker image 'reverseproxy' to Docker Hub
      run: docker push markus2101/reverseproxy:v1
